baseURL = 'https://comfy.guide/'
languageCode = 'en-us'
title = 'Comfy Guides'

[params]
git = 'https://github.com/AleDenshi/comfy.guide'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

